import { useState } from 'react';
import { submitAttestation } from '../api/attestation';
import { signEIP712Request } from '../web3/wallet';

export default function ExportModal({ tree, activeBranchId, profile, isOpen, onClose, walletAddress, signer, sessionId }) {
  const [format, setFormat] = useState('latex');
  const [copied, setCopied] = useState(false);

  const [attesting, setAttesting] = useState(false);
  const [attestResult, setAttestResult] = useState(null);
  const [attestError, setAttestError] = useState(null);

  if (!isOpen || !tree) return null;

  const activeBranch = tree.branches?.[activeBranchId];
  const nodes = tree.nodes || {};

  const reportSteps = [];
  if (activeBranch) {
    for (let i = 0; i < activeBranch.node_ids.length; i++) {
      const nid = activeBranch.node_ids[i];
      const node = nodes[nid];
      if (!node) continue;

      if (node.kind === 'answer') {
        const qNode = i > 0 ? nodes[activeBranch.node_ids[i - 1]] : null;
        reportSteps.push({
          step: reportSteps.length + 1,
          question: qNode?.prompt || 'Question Point',
          answer: node.answer || node.answer_option_id,
        });
      } else if (node.kind === 'result') {
        const resData = node.context?.result || {};
        reportSteps.push({
          step: reportSteps.length + 1,
          isResult: true,
          testUsed: node.context?.test_used || 'Statistical Test',
          significant: resData.significant || (resData.p_value < 0.05),
          pValue: resData.p_value,
          statistic: resData.statistic,
          df: resData.degrees_of_freedom,
          effectSize: node.context?.effect_size || {},
          interpretation: node.context?.interpretation,
        });
      }
    }
  }

  // generate LaTeX
  function generateLaTeX() {
    let tex = `\\documentclass[11pt, a4paper]{article}\n`;
    tex += `\\usepackage{amsmath, amssymb, booktabs, hyperref, geometry}\n`;
    tex += `\\geometry{margin=1in}\n\n`;
    tex += `\\title{\\textbf{Supplementary Research Rationale \\\\ Hypothesis Exploration Audit}}\n`;
    tex += `\\author{Bio-Block Scientific Workstation}\n`;
    tex += `\\date{\\today}\n\n`;
    tex += `\\begin{document}\n`;
    tex += `\\maketitle\n\n`;

    if (profile) {
      tex += `\\section{Dataset Profile Summary}\n`;
      tex += `\\begin{itemize}\n`;
      tex += `  \\item \\textbf{Observations (N):} ${profile.row_count?.toLocaleString() || 'N/A'}\n`;
      tex += `  \\item \\textbf{Variables Analyzed:} ${profile.column_count || 'N/A'}\n`;
      tex += `\\end{itemize}\n\n`;
    }

    tex += `\\section{Formal Mathematical Hypotheses}\n`;
    tex += `\\begin{equation}\n`;
    tex += `  H_0: \\mu_1 - \\mu_2 = 0 \\quad \\text{(Null Hypothesis: No difference in population parameters)}\n`;
    tex += `\\end{equation}\n`;
    tex += `\\begin{equation}\n`;
    tex += `  H_1: \\mu_1 - \\mu_2 \\neq 0 \\quad \\text{(Alternative Hypothesis: Non-zero difference in population parameters)}\n`;
    tex += `\\end{equation}\n\n`;

    tex += `\\section{Chronological Decision Audit Trail}\n`;
    tex += `\\begin{enumerate}\n`;
    reportSteps.forEach((s) => {
      if (s.isResult) {
        tex += `  \\item \\textbf{Statistical Output [${s.testUsed}]:} \\\\\n`;
        tex += `        Result: $p = ${s.pValue != null ? Number(s.pValue).toFixed(4) : 'N/A'}$ (${s.significant ? 'Statistically Significant, Reject $H_0$' : 'Statistically non-significant, Fail to reject $H_0$'}). \\\\\n`;
        if (s.statistic != null) tex += `        Test Statistic: $T = ${Number(s.statistic).toFixed(4)}$. \\\\\n`;
      } else {
        tex += `  \\item \\textbf{Decision Point:} ${s.question} \\\\\n`;
        tex += `        \\textbf{Selection:} \\textit{${s.answer}}\n`;
      }
    });
    tex += `\\end{enumerate}\n\n`;

    if (attestResult) {
      tex += `\\section{On-Chain Attestation}\n`;
      tex += `\\begin{itemize}\n`;
      if (attestResult.result_cid) tex += `  \\item \\textbf{IPFS Result CID:} \\texttt{${attestResult.result_cid}}\n`;
      if (attestResult.tx_hash) tex += `  \\item \\textbf{Sepolia Tx:} \\texttt{${attestResult.tx_hash}}\n`;
      tex += `\\end{itemize}\n\n`;
    }

    tex += `\\section{Conclusion \\& Methodological Justification}\n`;
    tex += `The statistical protocol followed an interactive decision tree to preserve alpha-error rates and verify distribution assumptions prior to hypothesis testing.\n\n`;
    tex += `\\end{document}\n`;
    return tex;
  }

  // generate Markdown
  function generateMarkdown() {
    let md = `# Supplementary Research Rationale & Audit Report\n\n`;
    md += `**Generated by:** Bio-Block Hypothesis Lab Workstation  \n`;
    md += `**Date:** ${new Date().toLocaleDateString()}  \n\n`;

    if (profile) {
      md += `## 1. Dataset Profile\n\n`;
      md += `- **Observations (N):** ${profile.row_count?.toLocaleString() || 'N/A'}\n`;
      md += `- **Variables Profiled:** ${profile.column_count || 'N/A'}\n\n`;
    }

    md += `## 2. Formal Hypotheses\n\n`;
    md += `- **$H_0$ (Null Hypothesis):** $\\mu_1 - \\mu_2 = 0$ (No difference in target parameter)\n`;
    md += `- **$H_1$ (Alternative Hypothesis):** $\\mu_1 - \\mu_2 \\neq 0$ (Non-zero difference in population parameters)\n\n`;

    md += `## 3. Decision Audit Trail\n\n`;
    reportSteps.forEach((s) => {
      if (s.isResult) {
        md += `### Step ${s.step}: Statistical Output — ${s.testUsed}\n\n`;
        md += `- **Status:** ${s.significant ? 'Statistically Significant (Reject $H_0$)' : 'Statistically Non-Significant (Fail to reject $H_0$)'}\n`;
        md += `- **p-value:** \`p = ${s.pValue != null ? Number(s.pValue).toFixed(6) : 'N/A'}\`\n`;
        if (s.statistic != null) md += `- **Statistic:** \`${Number(s.statistic).toFixed(4)}\`\n`;
        if (s.df != null) md += `- **df:** \`${s.df}\`\n`;
        md += `\n`;
      } else {
        md += `### Step ${s.step}: ${s.question}\n\n`;
        md += `> **Selection:** ${s.answer}\n\n`;
      }
    });

    if (attestResult) {
      md += `## On-Chain Attestation\n\n`;
      if (attestResult.result_cid) md += `- **IPFS Result CID:** \`${attestResult.result_cid}\`\n`;
      if (attestResult.tx_hash) md += `- **Sepolia Tx:** \`${attestResult.tx_hash}\`\n`;
      if (attestResult.etherscan_url) md += `- **Etherscan:** [View Transaction](${attestResult.etherscan_url})\n`;
      md += `\n`;
    }

    md += `## 4. Methodology Statement\n\n`;
    md += `This exploration followed a structured decision tree framework to ensure assumption checks (normality, variance homogeneity) preceded final model selection.\n`;
    return md;
  }

  const content = format === 'latex' ? generateLaTeX() : generateMarkdown();

  function handleCopy() {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleDownload() {
    const ext = format === 'latex' ? 'tex' : 'md';
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `hypothesis_report_${activeBranchId || 'branch'}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function handleAttest() {
    if (!walletAddress || !signer || !sessionId) return;

    setAttesting(true);
    setAttestError(null);
    setAttestResult(null);

    try {
      const encoder = new TextEncoder();
      const data = encoder.encode(content);
      const hashBuffer = await crypto.subtle.digest('SHA-256', data);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      const requestHash = hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');

      const datasetCID = `local-session-${sessionId}`;

      const { signature, timestamp, nonce } = await signEIP712Request(signer, {
        datasetCID,
        requestHash,
      });

      const result = await submitAttestation(sessionId, {
        walletAddress,
        signature,
        timestamp,
        nonce,
        requestHash,
        sourceCid: datasetCID,
        branchId: activeBranchId,
      });

      setAttestResult(result);
    } catch (err) {
      setAttestError(err.message || 'Attestation failed');
    } finally {
      setAttesting(false);
    }
  }

  function handleClose() {
    setAttestResult(null);
    setAttestError(null);
    onClose();
  }

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        background: 'rgba(0, 0, 0, 0.75)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 99999,
        padding: '20px',
      }}
    >
      <div
        style={{
          maxWidth: '750px',
          width: '100%',
          background: 'var(--bg-secondary)',
          border: '1px solid var(--border-strong)',
          borderRadius: 'var(--radius-card)',
          boxShadow: 'var(--shadow-md)',
          display: 'flex',
          flexDirection: 'column',
          maxHeight: '85vh',
          overflow: 'hidden',
        }}
      >
        <div
          style={{
            padding: '14px 18px',
            background: 'var(--bg-panel)',
            borderBottom: '1px solid var(--border-default)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--accent-amber)' }}>
            EXPORT SUPPLEMENTARY REPORT ({format.toUpperCase()})
          </div>
          <button className="btn btn-ghost btn-sm" onClick={handleClose}>
            ×
          </button>
        </div>

        <div style={{ padding: '12px 20px 0 20px', display: 'flex', gap: '8px', alignItems: 'center' }}>
          <button
            className={`btn btn-sm ${format === 'latex' ? 'btn-primary' : 'btn-ghost'}`}
            onClick={() => setFormat('latex')}
          >
            LaTeX (.tex)
          </button>
          <button
            className={`btn btn-sm ${format === 'markdown' ? 'btn-primary' : 'btn-ghost'}`}
            onClick={() => setFormat('markdown')}
          >
            Markdown (.md)
          </button>
        </div>

        <div style={{ padding: '12px 20px', flex: 1, minHeight: 0, overflowY: 'auto' }}>
          <pre
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '11px',
              color: 'var(--text-primary)',
              whiteSpace: 'pre-wrap',
              margin: 0,
              lineHeight: 1.5,
            }}
          >
            {content}
          </pre>
        </div>

        {(attestResult || attestError || attesting) && (
          <div className="attest-success" style={{ margin: '0 18px' }}>
            {attestResult && (
              <>
                <span>✓ ATTESTED ON-CHAIN</span>
                {attestResult.result_cid && <span>CID: {attestResult.result_cid.slice(0, 12)}…</span>}
                {attestResult.etherscan_url && (
                  <a href={attestResult.etherscan_url} target="_blank" rel="noopener noreferrer">
                    View on Etherscan ↗
                  </a>
                )}
              </>
            )}
            {attesting && <span>⏳ ATTESTING…</span>}
            {attestError && <span style={{ color: 'var(--accent-red)' }}>✕ {attestError}</span>}
          </div>
        )}

        <div
          style={{
            padding: '14px 20px',
            background: 'var(--bg-panel)',
            borderTop: '1px solid var(--border-default)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            flexWrap: 'wrap',
            gap: '8px',
          }}
        >
          <button className="btn btn-ghost btn-sm" onClick={handleClose}>
            CLOSE
          </button>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn btn-ghost btn-sm" onClick={handleCopy}>
              {copied ? 'COPIED' : 'COPY TO CLIPBOARD'}
            </button>
            <button className="btn btn-primary btn-sm" onClick={handleDownload}>
              DOWNLOAD {format.toUpperCase()} FILE
            </button>

            {walletAddress && !attestResult && (
              <button
                className="btn btn-sm btn-attest"
                onClick={handleAttest}
                disabled={attesting || !walletAddress}
              >
                {attesting
                  ? '⏳ ATTESTING…'
                  : !walletAddress
                  ? '🔒 CONNECT WALLET FIRST'
                  : '⛓ SAVE & ATTEST ON-CHAIN'}
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
