name: Python Backend CI

on:
  push:
    paths:
      - "python_backend/**"
  pull_request:
    paths:
      - "python_backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Install python
        working-directory: python_backend
        run: uv python install

      - name: Install dependencies
        working-directory: python_backend
        run: uv sync --frozen

      - name: Run tests
        working-directory: python_backend
        run: uv run pytest -q
